# Generated by Django 4.2.23 on 2025-07-27 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_annual_amount', models.DecimalField(decimal_places=2, help_text='Maximum yearly amount a beneficiary in this category can receive', max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received in this assessment', max_digits=10),
        ),
        migrations.AddField(
            model_name='assessment',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='dob',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Amount a beneficiary receives per month', max_digits=10)),
                ('next_program', models.ForeignKey(blank=True, help_text='Optional: Promote to this program after conditions are met', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.program')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='core.beneficiarycategory'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='core.program'),
        ),
    ]
