# Generated by Django 4.2.23 on 2023-11-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beneficiarycategory_assessment_amount_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('beneficiary', 'Beneficiaries'), ('case', 'Cases'), ('assessment', 'Assessments'), ('case_note', 'Case Notes'), ('program', 'Programs'), ('category', 'Categories')], max_length=20)),
                ('fields', models.TextField(help_text='JSON array of field names to include in the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.TextField(blank=True, help_text='JSON object of filters to apply')),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF')], default='excel', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.reporttemplate')),
            ],
        ),
    ]