# Generated by Django 4.2.23 on 2025-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role_referral_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Beneficiary's annual income amount", max_digits=10),
        ),
    ]
